# Generated by Django 3.2.18 on 2023-07-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gpa', models.FloatField()),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.department')),
            ],
        ),
    ]
