# Generated by Django 3.2.18 on 2023-07-19 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 7, 19, 14, 28, 47, 588747, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
